### PR TITLE
[Blog]Pipelining Service Mesh Specifications

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
@bridgetkromhout, any changes that you think should be made?

**Comment by bridgetkromhout** [comment]
Hi Lee, let's get this on the agenda for today's community call to make sure it's all good! (And perhaps update the publication date?)

**Comment by leecalcote** [comment]
@bridgetkromhout, I neglected to follow up on this post in our call yesterday. A couple of final tweaks, including date, have been updated by @debo19. All clear from my side. 👍

**Comment by leecalcote** [comment]
@keithmattix and @nicholasjackson the SMI Conformance GitHub Action ties into the controller SDK work well.

**Review by keithmattix — APPROVED** [review]

**Comment by bridgetkromhout** [comment]
Sorry for the delay - and thanks for this blog post! Let's get a tweet out about it Monday?

**Pull request merged**
