### PR TITLE
Adding new blog post

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Adding blog post written with @michelleN for SMI joining CNCF

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi @flynnduism, can you take a look at https://deploy-preview-30--smi-spec.netlify.com/blog/ and suggest what I'm missing or what the theme needs? Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @flynnduism - I would love to publish this blog post this morning! It would be nice if the remaining issue in #32 is a fast fix. Thanks!

**Comment by bridgetkromhout** [comment]
Looks great! I think this is ready to merge.

**Comment by lachie83** [comment]
LGTM. Thanks Bridget and Ronan

**Pull request merged**
