### PR TITLE
Update Consul Logo

### PR DESCRIPTION
**Pull request by t-eckert**
Hello SMI team! We at Consul have updated our logo and I thought I would lend a hand and update the logo for the SMI site.

I see that the logo I've added is a bigger file size than the previous one, but it seemed comparable to other logo file sizes in the directory. Please let me know if you need a more compressed version.

Thank you for all the great work you do.

### CODE REVIEW

**Comment by t-eckert** [comment]
Looking at the deployment preview, it looks like the larger file size has made the logo larger on the page. I'll shrink the file to stop that.

**Comment by t-eckert** [comment]
I replaced the vertical logo with the horizontal logo as it seems to fit better with how you have things laid out.

**Review by flynnduism — APPROVED** [review]
Thanks, testing this via [the preview](https://deploy-preview-68--smi-spec.netlify.app/) it looks good to me!

**Comment by t-eckert** [comment]
Great! I'll go ahead and merge it.

**Review by bridgetkromhout — APPROVED** [review]

**Pull request merged**
